### ISSUE TITLE
Use low quaility camera by default

### ISSUE THREAD

**Issue by lkiesow** [virtUOS/bigbluebutton-ansible#5]

**Comment by lkiesow** [comment]
There is `/var/www/bigbluebutton/client/conf/profiles.xml` but that does not seem to have any effect

**Comment by lkiesow** [comment]
The configuration is in `/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml`

```
    cameraProfiles:
    - id: low
      name: Low quality
      default: true
      bitrate: 100
    - id: medium
      name: Medium quality
      default: false
      bitrate: 200
    - id: high
      name: High quality
      default: false
      bitrate: 500
    - id: hd
      name: High definition
      default: false
      bitrate: 800
```
